import { describe, it, expect } from "vitest";

function setupDom() {
  document.body.innerHTML = `
    <div id="turnIndicator"></div>
    <div id="turnCounter"></div>
    <div id="opponentSummary"></div>
    <div id="opponentAlert"></div>
    <ul id="rulesList"></ul>
    <div id="expansionRules"></div>
    <div id="cardLegend"></div>
    <div id="handCounts"></div>
    <div id="archivePile"></div>
    <div id="activeCards"></div>
    <div id="handCards"></div>
    <div id="tradeInfo"></div>
    <div id="deckInfo"></div>
    <div id="discardInfo"></div>
    <div id="boardDeckStack"></div>
    <div id="boardDiscardStack"></div>
    <div id="deckZone"></div>
    <div id="discardZone"></div>
    <div id="archiveZone"></div>
    <div id="activeZone"></div>
    <div id="handZone"></div>
    <div id="feedbackCaption"></div>
    <div id="goldRace"></div>
    <div id="goldRacePlayer"></div>
    <div id="goldRaceOpponent"></div>
    <div id="turnReplayPanel"></div>
    <div id="turnReplayCards"></div>
    <div id="turnReplayMeta"></div>
    <button id="turnReplayClose"></button>
    <div id="archiveInspectOverlay"></div>
    <div id="archiveInspectTitle"></div>
    <div id="archiveInspectMeta"></div>
    <div id="archiveInspectCards"></div>
    <button id="archiveInspectClose"></button>
    <div id="feedbackLayer"></div>
    <span id="deckAnchor"></span>
    <span id="handAnchor"></span>
    <span id="activeAnchor"></span>
    <span id="archiveAnchor"></span>
    <span id="discardAnchor"></span>
    <button id="themeClassic"></button>
    <button id="themePixel"></button>
    <button id="openHowToPlay"></button>
    <button id="motionToggle"></button>
    <div id="howToPlayOverlay"></div>
    <button id="closeHowToPlay"></button>
    <div id="tradesOverlay"></div>
    <button id="openTradesModal"></button>
    <button id="closeTradesModal"></button>
    <button id="tradeBronze"></button>
    <button id="tradeSilver"></button>
    <button id="tradeGems"></button>
    <button id="tradePlatinum"></button>
    <button id="tradeAncientsArchive"></button>
    <button id="tradePearl"></button>
    <button id="tradeObsidian"></button>
    <button id="tradeAmethyst"></button>
    <button id="tradeAsh"></button>
    <button id="tradeEmber"></button>
    <button id="tradeElectrumDraw"></button>
    <button id="tradeMint"></button>
    <button id="tradeHallmark"></button>
    <button id="endTurn"></button>
    <button id="undoPlays"></button>
    <div id="winnerPanel"></div>
    <div id="winnerText"></div>
    <button id="restartGame"></button>
    <div id="winnerOverlay"></div>
    <div id="winnerModalText"></div>
    <div id="winnerModalMessage"></div>
    <div id="winnerStats"></div>
    <button id="restartGameModal"></button>
    <div id="confirmOverlay"></div>
    <div id="confirmSummary"></div>
    <div id="confirmCards"></div>
    <button id="cancelArchive"></button>
    <button id="confirmArchive"></button>
    <div id="turnOverlay"></div>
    <div id="overlayTitle"></div>
    <button id="startTurn"></button>
    <div id="cpuTurnOverlay"></div>
    <div id="cpuTurnSummary"></div>
    <button id="cpuTurnConfirm"></button>
    <div id="modeOverlay"></div>
    <button id="offlineMode"></button>
    <button id="cpuMode"></button>
    <button id="onlineMode"></button>
    <div id="formatOverlay"></div>
    <button id="formatCore"></button>
    <button id="formatExpanded"></button>
    <button id="formatAncient"></button>
    <button id="formatMystic"></button>
    <button id="formatMinted"></button>
    <div id="cpuOverlay"></div>
    <button id="cpuEasy"></button>
    <button id="cpuMedium"></button>
    <button id="cpuHard"></button>
    <div id="onlineChoiceOverlay"></div>
    <div id="hostOverlay"></div>
    <div id="guestOverlay"></div>
    <button id="hostFormatCore"></button>
    <button id="hostFormatExpanded"></button>
    <button id="hostFormatAncient"></button>
    <button id="hostFormatMystic"></button>
    <button id="hostFormatMinted"></button>
    <input id="playerNameInput" />
    <input id="roomCodeInput" />
    <button id="createRoom"></button>
    <button id="chooseCreate"></button>
    <button id="chooseJoin"></button>
    <button id="backToChoiceHost"></button>
    <button id="backToChoiceGuest"></button>
    <button id="joinRoom"></button>
    <button id="readyButton"></button>
    <button id="readyButtonGuest"></button>
    <input id="guestNameInput" />
    <input id="guestRoomCodeInput" />
    <button id="copyRoomCode"></button>
    <div id="hostStatus"></div>
    <div id="guestStatus"></div>
    <div id="woodOverlay"></div>
    <div id="woodMessage"></div>
    <div id="woodSubOptions"></div>
    <button id="woodConfirm"></button>
    <button id="woodCancel"></button>
    <div id="efficiencyOverlay"></div>
    <div id="efficiencyMessage"></div>
    <div id="efficiencyOptions"></div>
    <button id="efficiencyConfirm"></button>
    <button id="efficiencyCancel"></button>
    <div id="gemTutorOverlay"></div>
    <div id="gemTutorOptions"></div>
    <button id="gemTutorConfirm"></button>
    <button id="gemTutorCancel"></button>
    <div id="choiceCostOverlay"></div>
    <div id="choiceCostMessage"></div>
    <div id="choiceCostOptions"></div>
    <button id="choiceCostConfirm"></button>
    <button id="choiceCostCancel"></button>
    <div id="poolCostOverlay"></div>
    <div id="poolCostMessage"></div>
    <div id="poolCostOptions"></div>
    <button id="poolCostConfirm"></button>
    <button id="poolCostCancel"></button>
    <div id="archiveTutorOverlay"></div>
    <div id="archiveTutorMessage"></div>
    <div id="archiveTutorOptions"></div>
    <button id="archiveTutorConfirm"></button>
    <button id="archiveTutorCancel"></button>
    <div id="handArchiveOverlay"></div>
    <div id="handArchiveMessage"></div>
    <div id="handArchiveOptions"></div>
    <button id="handArchiveConfirm"></button>
    <button id="handArchiveCancel"></button>
    <div id="actionToast"></div>
    <div id="actionToastText"></div>
  `;
}

describe("app bootstrap", () => {
  it("initializes without throwing", async () => {
    setupDom();
    await import("../app.js");

    document.getElementById("offlineMode").click();
    document.getElementById("formatCore").click();

    expect(document.getElementById("turnIndicator").textContent).toContain("Player");
    expect(document.getElementById("turnCounter").textContent).toContain("Turn");
  });
});
